repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=500']
      - id: check-json
      - id: detect-private-key

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black"]

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.262'
    hooks:
      - id: ruff
        args: ["--fix"]

  - repo: local
    hooks:
      - id: tests
        name: Run Tests
        entry: python -m pytest
        language: system
        types: [python]
        pass_filenames: false
        
      - id: monte-carlo-tests
        name: Monte Carlo Tests
        entry: python -m unittest tests/models/test_monte_carlo_*.py
        language: system
        pass_filenames: false
        files: ^models/monte_carlo/.*\.py$
      
      - id: monte-carlo-performance
        name: Monte Carlo Performance
        entry: python -m unittest tests/models/test_monte_carlo_regression.py
        language: system
        pass_filenames: false
        files: ^models/monte_carlo/.*\.py$

      - id: check-monte-carlo-dependencies
        name: Check Monte Carlo Dependencies
        entry: python tools/check_monte_carlo_dependencies.py
        language: system
        pass_filenames: false
        files: ^models/monte_carlo/.*\.py$