name: Monte Carlo Performance

on:
  push:
    paths:
      - 'models/monte_carlo/**'
      - 'tests/models/test_monte_carlo_*.py'
  pull_request:
    paths:
      - 'models/monte_carlo/**'
      - 'tests/models/test_monte_carlo_*.py'

jobs:
  performance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history to compare with baseline

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Monte Carlo Tests
        run: |
          python -m unittest tests/models/test_monte_carlo_cache_performance.py
          python -m unittest tests/models/test_monte_carlo_optimizations.py

      - name: Run Performance Regression Tests
        run: |
          python -m unittest tests/models/test_monte_carlo_regression.py > test_output.log 2>&1
          cat test_output.log

      - name: Check for Performance Regressions
        run: |
          if grep -q "PERFORMANCE REGRESSION" test_output.log; then
            echo "::warning::Performance regression detected!"
            grep "PERFORMANCE REGRESSION" test_output.log
            
            # Don't fail the build, just warn
            # Use exit 1 to fail the build if performance is critical
            # exit 1
          fi

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: monte-carlo-test-results
          path: |
            test_output.log
            tests/models/benchmark_results.json

      - name: Performance Trend Analysis
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          # Parse benchmark results and generate trend graph
          python tools/analyze_monte_carlo_performance.py

      - name: Upload Performance Trend Analysis
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v3
        with:
          name: monte-carlo-performance-trends
          path: |
            performance_trends*.png
            performance_report.md